import { Product } from "@/types";

export const mockProducts: Product[] = [
  {
    id: "1",
    slug: "focus-graphic-tee-black",
    name: "Focus Graphic Tee — Black",
    description:
      "Premium heavyweight cotton tee with the signature FocusTM graphic print. Customizable name and number on request.",
    price: 15000,
    images: [],
    category: "shirts",
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Black"],
    customizable: true,
    stock: 24,
    featured: true,
  },
  {
    id: "2",
    slug: "lagos-print-tee",
    name: "Lagos Print Tee",
    description: "Limited edition Lagos cityscape print tee — part of the FocusTM city series.",
    price: 16500,
    images: [],
    category: "shirts",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "White"],
    customizable: false,
    stock: 18,
    featured: true,
  },
  {
    id: "3",
    slug: "ftm-snapback-cap",
    name: "FTM Snapback Cap",
    description: "Structured snapback with embroidered FTM emblem. One size fits most.",
    price: 9000,
    images: [],
    category: "caps",
    sizes: ["One Size"],
    colors: ["Black", "Navy"],
    customizable: true,
    stock: 40,
    featured: true,
  },
  {
    id: "4",
    slug: "focus-hoodie-charcoal",
    name: "Focus Hoodie — Charcoal",
    description: "Heavyweight fleece hoodie with embroidered FocusTM crest.",
    price: 28000,
    images: [],
    category: "tops",
    sizes: ["M", "L", "XL", "XXL"],
    colors: ["Charcoal"],
    customizable: true,
    stock: 12,
    featured: true,
  },
];
